version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iam-base-project"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qz77aemws7xb"
s3_prefix = "iam-base-project"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
